
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joe
 */
public class SEAT extends javax.swing.JFrame {

    /**
     * Creates new form SEAT
     */String ele, elem;
       String mydriver="com.mysql.jdbc.Driver";  
        String myconn="jdbc:mysql://localhost:3306/bus?zeroDateTimeBehavior=convertToNull";
  	String UID ="root";
  	String pwd = "";
        
     public int FrameWidth=750,FrameHeight=1400;
    public SEAT() {
        initComponents();
    }
     public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    public SEAT(String x)
    {
        elem=x;
        initComponents();
    }
    public void GraphicBus(String value)
         {
             ele=value;
           }


 public void FrameBar(String name)
     {
      //    GraphicBus(name);
           ele=name;
          setBounds(100,100,FrameWidth,FrameHeight);
          setSize(2000,2000);
          setVisible(true);
   }
    
     
    
   public void paint(Graphics g)
          {
     
          int i,j,count=1,x=0,cor=0,k=0;
            boolean t;
           String scount;
    try
      {
      Connection con=DriverManager.getConnection(myconn, UID, pwd);  
      Class.forName(mydriver);
      Statement s=con.createStatement();
      
      
      ResultSet rs=s.executeQuery("SELECT * from bus1 WHERE BUSID='"+elem+"' ORDER BY SEAT ASC");                        
g.setColor(Color.RED);
                      g.fillOval(700,300,60,60);
                      g.drawString("BOOKED",700,300);
                      g.setColor(Color.GREEN);
                      g.fillOval(700,400,60,60);
                      g.drawString("VACANT",700,400);
          
                      
                   while(rs.next())
             {
                 
                 t=rs.next();
                 rs.previous();
                 x=rs.getInt("SEAT");
               
                count=1;
                for(i=0;i<10;i++)
                {
               cor=0;
            for(j=1;j<=4;j++,count++)
             {  
                 if(j==3)
                  cor=60;
                 
                 if(x==count)
                    {
          scount=Integer.toString(count);
          g.setColor(Color.RED);
          g.fillOval(60*j+cor,100+60*i+20,50,50);
           g.drawString(scount,60*j+cor,100+60*i+20);
                 k=1;
                  if(t)
                 {
                  rs.next();
                  x=rs.getInt("SEAT");
                     }
                      t=rs.next();
                         rs.previous();
                               
}
   else
         
           {
            scount=Integer.toString(count);
            g.setColor(Color.GREEN);
            g.fillOval(60*j+cor,100+60*i+20,50,50);     
            g.drawString(scount,60*j+cor,100+60*i+20);
             }   
                   
              }
         }
      }
     if(k==0)
  {
        for(i=0;i<10;i++)
                {
               cor=0;
            for(j=1;j<=4;j++,count++)
             {  
                 if(j==3)
                  cor=60;
            scount=Integer.toString(count);
            g.setColor(Color.GREEN);
            g.fillOval(60*j+cor,100+60*i+20,50,50);
           g.drawString(scount,60*j+cor,100+60*i+20);
             }
               }
}

con.close(); 
 } 
catch(Exception e)
{
System.out.println(e);
}

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
